version: "3.1"

services:
  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
